// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/queue.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/queue.go -destination=internal/core/ports/mocks/queue_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/kubilayciftci/insider-one-notification/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageQueue is a mock of MessageQueue interface.
type MockMessageQueue struct {
	ctrl     *gomock.Controller
	recorder *MockMessageQueueMockRecorder
	isgomock struct{}
}

// MockMessageQueueMockRecorder is the mock recorder for MockMessageQueue.
type MockMessageQueueMockRecorder struct {
	mock *MockMessageQueue
}

// NewMockMessageQueue creates a new mock instance.
func NewMockMessageQueue(ctrl *gomock.Controller) *MockMessageQueue {
	mock := &MockMessageQueue{ctrl: ctrl}
	mock.recorder = &MockMessageQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageQueue) EXPECT() *MockMessageQueueMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessageQueue) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMessageQueueMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessageQueue)(nil).Close))
}

// Publish mocks base method.
func (m *MockMessageQueue) Publish(ctx context.Context, notification *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockMessageQueueMockRecorder) Publish(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMessageQueue)(nil).Publish), ctx, notification)
}

// PublishDLQ mocks base method.
func (m *MockMessageQueue) PublishDLQ(ctx context.Context, notification *domain.Notification, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDLQ", ctx, notification, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDLQ indicates an expected call of PublishDLQ.
func (mr *MockMessageQueueMockRecorder) PublishDLQ(ctx, notification, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDLQ", reflect.TypeOf((*MockMessageQueue)(nil).PublishDLQ), ctx, notification, reason)
}

// PublishRetry mocks base method.
func (m *MockMessageQueue) PublishRetry(ctx context.Context, notification *domain.Notification, delay time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRetry", ctx, notification, delay)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRetry indicates an expected call of PublishRetry.
func (mr *MockMessageQueueMockRecorder) PublishRetry(ctx, notification, delay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRetry", reflect.TypeOf((*MockMessageQueue)(nil).PublishRetry), ctx, notification, delay)
}
