// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/repository.go -destination=internal/core/ports/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/kubilayciftci/insider-one-notification/internal/core/domain"
	ports "github.com/kubilayciftci/insider-one-notification/internal/core/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockNotificationRepository) Cancel(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockNotificationRepositoryMockRecorder) Cancel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockNotificationRepository)(nil).Cancel), ctx, id)
}

// Create mocks base method.
func (m *MockNotificationRepository) Create(ctx context.Context, n *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepositoryMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepository)(nil).Create), ctx, n)
}

// CreateBatch mocks base method.
func (m *MockNotificationRepository) CreateBatch(ctx context.Context, notifications []*domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, notifications)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockNotificationRepositoryMockRecorder) CreateBatch(ctx, notifications any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockNotificationRepository)(nil).CreateBatch), ctx, notifications)
}

// GetByBatchID mocks base method.
func (m *MockNotificationRepository) GetByBatchID(ctx context.Context, batchID uuid.UUID) ([]*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBatchID", ctx, batchID)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBatchID indicates an expected call of GetByBatchID.
func (mr *MockNotificationRepositoryMockRecorder) GetByBatchID(ctx, batchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBatchID", reflect.TypeOf((*MockNotificationRepository)(nil).GetByBatchID), ctx, batchID)
}

// GetByID mocks base method.
func (m *MockNotificationRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotificationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotificationRepository)(nil).GetByID), ctx, id)
}

// GetDueScheduled mocks base method.
func (m *MockNotificationRepository) GetDueScheduled(ctx context.Context) ([]*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDueScheduled", ctx)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDueScheduled indicates an expected call of GetDueScheduled.
func (mr *MockNotificationRepositoryMockRecorder) GetDueScheduled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDueScheduled", reflect.TypeOf((*MockNotificationRepository)(nil).GetDueScheduled), ctx)
}

// IncrementRetry mocks base method.
func (m *MockNotificationRepository) IncrementRetry(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetry", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetry indicates an expected call of IncrementRetry.
func (mr *MockNotificationRepositoryMockRecorder) IncrementRetry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetry", reflect.TypeOf((*MockNotificationRepository)(nil).IncrementRetry), ctx, id)
}

// List mocks base method.
func (m *MockNotificationRepository) List(ctx context.Context, filter ports.ListFilter) ([]*domain.Notification, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockNotificationRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotificationRepository)(nil).List), ctx, filter)
}

// UpdateStatus mocks base method.
func (m *MockNotificationRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNotificationRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateStatus), ctx, id, status)
}
