name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: goinstall
          version: v2.1.6

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: Run unit tests
        run: go test ./internal/core/... -v -count=1 -race

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: Run integration tests
        run: go test ./internal/adapters/... -v -count=1 -tags=integration -timeout=300s

  build:
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: Build API
        run: go build ./cmd/api
      - name: Build Worker
        run: go build ./cmd/worker

  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t insider-one-notification:test .
